PSPSDK: test/main.cpp File Reference
main.cpp File Reference
#include <pspkernel.h>
#include <pspdebug.h>
#include <pspctrl.h>
#include <psputils.h>
#include <pspdisplay.h>
#include <psprtc.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
Data Structures
struct BITMAPFILEHEADER
struct BITMAPINFOHEADER
struct Image
Macros
#define BMP_FILE_PATH "ms0:/data/asciiart.bmp"
#define OUTPUT_DIR "ms0:/data/"
#define ASCII_FILE_SUFFIX "_ascii_art.txt"
#define COLOR_FILE_SUFFIX "_color.dat"
#define TARGET_WIDTH 80
Functions
PSP_MODULE_INFO ("PSP_ASCIIArt", 0, 1, 0)
PSP_MAIN_THREAD_ATTR (THREAD_ATTR_USER)
Image * load_bmp (const char *path)
void free_image (Image *img)
Image * resize_image (const Image *src, int targetWidth)
char * convert_to_ascii (const Image *img)
void make_filename (char *buffer, int bufferSize, const char *suffix)
int save_text_file (const char *path, const char *text)
int save_color_data (const char *path, const Image *img)
int wait_for_button_press ()
int main (void)
Variables
const char * asciiChars = "@#S%?*+;:,. "
int asciiCharsLen = 12
Macro Definition Documentation
ASCII_FILE_SUFFIX
#define ASCII_FILE_SUFFIX "_ascii_art.txt"
Referenced by main().
BMP_FILE_PATH
#define BMP_FILE_PATH "ms0:/data/asciiart.bmp"
Referenced by main().
COLOR_FILE_SUFFIX
#define COLOR_FILE_SUFFIX "_color.dat"
Referenced by main().
OUTPUT_DIR
#define OUTPUT_DIR "ms0:/data/"
Referenced by make_filename().
TARGET_WIDTH
#define TARGET_WIDTH 80
Referenced by main().
Function Documentation
convert_to_ascii()
char * convert_to_ascii (const Image * img)
References asciiChars, asciiCharsLen, Image::height, NULL, Image::pixels, and Image::width.
Referenced by main().
free_image()
void free_image (Image * img)
References Image::pixels.
Referenced by main().
load_bmp()
Image * load_bmp (const char * path)
References BITMAPFILEHEADER::bfOffBits, BITMAPFILEHEADER::bfType, BITMAPINFOHEADER::biBitCount, BITMAPINFOHEADER::biCompression, BITMAPINFOHEADER::biHeight, BITMAPINFOHEADER::biWidth, fp, Image::height, NULL, Image::pixels, and Image::width.
Referenced by main().
main()
int main (void)
References ASCII_FILE_SUFFIX, BMP_FILE_PATH, SceCtrlData::Buttons, COLOR_FILE_SUFFIX, convert_to_ascii(), free_image(), Image::height, load_bmp(), make_filename(), PSP_CTRL_CROSS, PSP_CTRL_START, pspDebugScreenInit(), pspDebugScreenPrintf(), resize_image(), save_color_data(), save_text_file(), sceCtrlPeekBufferPositive(), sceDisplayWaitVblankStart(), sceKernelDelayThread(), sceKernelExitGame(), sceKernelSleepThread(), TARGET_WIDTH, wait_for_button_press(), and Image::width.
Referenced by _main(), and pspDebugGetStackTrace().
make_filename()
void make_filename (char * buffer, int bufferSize, const char * suffix)
References OUTPUT_DIR, and sceRtcGetCurrentTick().
Referenced by main().
PSP_MAIN_THREAD_ATTR()
PSP_MAIN_THREAD_ATTR (THREAD_ATTR_USER)
PSP_MODULE_INFO()
PSP_MODULE_INFO ("PSP_ASCIIArt" , 0 , 1 , 0)
resize_image()
Image * resize_image (const Image * src, int targetWidth)
References Image::height, NULL, Image::pixels, and Image::width.
Referenced by main().
save_color_data()
int save_color_data (const char * path, const Image * img)
References fp, Image::height, Image::pixels, and Image::width.
Referenced by main().
save_text_file()
int save_text_file (const char * path, const char * text)
References fp.
Referenced by main().
wait_for_button_press()
int wait_for_button_press ()
References SceCtrlData::Buttons, pspDebugScreenPrintf(), sceCtrlReadBufferPositive(), and sceDisplayWaitVblankStart().
Referenced by main().
Variable Documentation
asciiChars
const char* asciiChars = "@#S%?*+;:,. "
Referenced by convert_to_ascii().
asciiCharsLen
int asciiCharsLen = 12
Referenced by convert_to_ascii().